export const texto11=[
    <p><small># Varaveis guardam um valor, como uma gaveta com uma etiqueta</small></p>,
    <p><small># As 3 variáveis simples são:</small></p>,
    <p> </p>,
    <p><small># inteiro</small></p>,
    <p>minhaQuantidade <strong>=</strong> 6</p>,
    <p> </p>,
    <p><small># string (palavra)</small></p>,
    <p>minhaFruta <strong>=</strong> 'melancia'</p>,
    <p> </p>,
    <p><small># booleano (True ou False)</small></p>,
    <p>statusAtivo <strong>= True</strong></p>
]
export const texto12=[
    <p><small># If executa o bloco de código caso a condicao seja True</small></p>,
    <p><small># Esse bloco e definido pelo que tem 1 Tab a mais que ele</small></p>,
    <p>quantidade <strong>=</strong> 13</p>,
    <p><strong>if</strong> quantidade <strong>{'>'}</strong> 10 <strong>:</strong></p>,
    <p><span/><strong>print(</strong>'maior que 10' <strong>)<strong></strong></strong></p>,
    <p> </p>,
    <p><small># Elif executa o bloco de código caso<strong>:</strong></small></p>,
    <p><small># Nao tenha entrado no bloco de cima & a condicao seja True</small></p>,
    <p>quantidade <strong>=</strong> 7</p>,
    <p><strong>if</strong> quantidade <strong>{'>'}</strong> 10 <strong>:</strong></p>,
    <p><span/><strong>print(</strong> 'maior que 10' <strong>)</strong></p>,
    <p><strong>elif</strong> quantidade <strong>{'>'}</strong> 5 <strong>:</strong></p>,
    <p><span/><strong>print(</strong> 'maior que 5' <strong>)</strong></p>,
    <p> </p>,
    <p><small># Else executa o bloco de código caso todos os blocos derem False</small></p>,
    <p>quantidade <strong>=</strong> 7</p>,
    <p><strong>if</strong> quantidade <strong>{'>'}</strong> 10 <strong>:</strong></p>,
    <p><span/><strong>print(</strong> 'maior que 10' <strong>)</strong></p>,
    <p><strong>else :</strong></p>,
    <p><span/><strong>print(</strong> 'menor ou igual a 10' <strong>)</strong></p>,
]
