export const texto21=[
    <p><small># Funcao e um bloco de codigo executado quando seu nome e chamado</small></p>,
    <p> </p>,
    <p><small># Criar funcao</small></p>,
    <p><strong>def</strong> minhaFuncao<strong>(</strong><strong>)</strong>:</p>,
    <p><span/>print<strong>(</strong> "Fui chamada" <strong>)</strong></p>,
    <p> </p>,
    <p><small># Chamar funcao</small></p>,
    <p>minhaFuncao<strong>(</strong><strong>)</strong></p>,
]
export const texto22=[
    <p><small># Os parametros sao escolhidos na criacao da funcao</small></p>,
    <p><small># E sao passados na hora de chamar a funcao, a ordem importa</small></p>,
    <p> </p>,
    <p><small># Criar funcao</small></p>,
    <p><strong>def</strong> compareOsDois<strong>(</strong> num1 <strong>,</strong> num2 <strong>)</strong>:</p>,
    <p><span/><strong>if</strong> num1 <strong>{'>'}</strong> num2 <strong>:</strong></p>,
    <p><span/><span/><strong>print<strong>(</strong></strong> 'o primeiro e maior' <strong><strong>)</strong></strong></p>,
    <p><span/><strong>elif</strong> num1 <strong>{'=='}</strong> num2 <strong>:</strong></p>,
    <p><span/><span/><strong>print<strong>(</strong></strong> 'sao iguais' <strong><strong>)</strong></strong></p>,
    <p><span/><strong>else :</strong></p>,
    <p><span/><span/><strong>print<strong>(</strong></strong> 'o segundo e maior' <strong><strong>)</strong></strong></p>,
    <p> </p>,
    <p><small># Chamar funcao</small></p>,
    <p>compareOsDois<strong>(</strong> 7 <strong>,</strong> 5 <strong>)</strong></p>,
    <p>compareOsDois<strong>(</strong> 4 <strong>,</strong> 4 <strong>)</strong></p>,
]
